title: "Sandbox Minimal Mistakes"
description: "Test sidebar nav"

url: "https://TON-USER.github.io"
baseurl: "/mm-sandbox"   # adapte au nom du repo

theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

markdown: kramdown
highlighter: rouge

locale: fr
timezone: Europe/Paris

plugins:
  - jekyll-include-cache

# archives (pas cruciaux pour le test mais propres)
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# par d√©faut pour les pages (layout single)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

search: false
